CREATE SCHEMA PharmacyDB;
USE PharmacyDB;

CREATE TABLE IF NOT EXISTS Customers (
    Phone CHAR(10) PRIMARY KEY CHECK (Phone REGEXP '^[0-9]{10}$'),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    City VARCHAR(50) NOT NULL,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Drugs (
    ID INT PRIMARY KEY,
    ExpDate DATE NOT NULL,
    Qty INT NOT NULL,
    Price INT NOT NULL,
    D_Use VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS DrugNames (
    ID INT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID) REFERENCES Drugs(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Images (
    ID INT PRIMARY KEY,
    Image LONGBLOB,
    FOREIGN KEY (ID) REFERENCES Drugs(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Orders (
    O_ID VARCHAR(100) PRIMARY KEY,
    PhoneNumber CHAR(10) NOT NULL,
    FOREIGN KEY(PhoneNumber) REFERENCES Customers(Phone) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OrderItems (
    O_ID VARCHAR(100),
    Item_Name VARCHAR(100),
    Item_Qty INT NOT NULL,
    PRIMARY KEY (O_ID, Item_Name),
    FOREIGN KEY (O_ID) REFERENCES Orders(O_ID) ON DELETE CASCADE
);
